sudo: false
language: cpp
compiler:
- gcc
- clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
- curl -O http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-Linux-x86_64.tar.gz
- tar xfz cmake-3.3.0-rc4-Linux-x86_64.tar.gz
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
script:
- ./cmake-3.3.0-rc4-Linux-x86_64/bin/cmake . -DASI_RUNTIMECOMMAND_ENGINE_EXTRAS=ON
- make -j5
- ./cmake-3.3.0-rc4-Linux-x86_64/bin/ctest . --output-on-failure
- ./cmake-3.3.0-rc4-Linux-x86_64/bin/cpack .
before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: P7AYlPdMGrigGUrrfiqIPNSs8BtV/jJh7UWkUrqf1+v8UnoqQKkS6p2hBjMk7FTaQ2qBpHh9mqrmEO3Sj2T6A0JHt80S2JtAmN03Q4H8PNKPkDDj3vqh57MrEPDYnQ4iFYzcMQRDBZjLVSGuaySe0IteJrDlxohYuRAHMq135rftFIDN5z41O7ZsO6t1qLYamsDw/qg3iavn5+GiN1odzQGmG2STDyKu/h2v9UfYtMXWuyB7Y85cK7NpEkgRQ1Fe+NerOYYJ8wTe2133z9XVq1vQSUHu+WOuCkIVUQJdWndNY/Vn786qE5VZJVKX+ilG9OoPDIOqRYbZWpzuenCiVEVta8IueLFrWmSjR4SaxDOrT2ThAv/GNewknDPHzV7x1V8RKyKlljzGbdU4DL3aL6l5URI9hSwUwGitxS61tEbJLRid3dHxWp8tC+f8bYZWY1B22lZsusPELTpUy+9uBs5RbCmZnHqkRR6rwgXniAZFuaBwU80cX1sE7d9qKGiviC+3Ad4GnpKN49xNghIttTED+nrhbIN1ndQXT/O14Se+VnLBz4L1s3rGUJoaPUG0Wu2D0SzpklXDeVhVYIF05F21biN7MKPphotMcusBzoMEdtToD9VCiNFSOQKUlBCkNp5FYIChxyLeEWxIPf/WPccqVwYtRfzffMJWtb77ZFE=
  file_glob: true
  file: "*.tar.Z"
  skip_cleanup: true
  on:
    tags: true
    repo: geoffviola/RuntimeCommandEngine
os:
- linux
