sudo: false
language: cpp
compiler:
- gcc
- clang
before_install:
- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
- sudo apt-get update -qq
install:
- ls /usr/local/bin
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
- curl -O http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-Linux-x86_64.tar.gz
- tar xfz cmake-3.3.0-rc4-Linux-x86_64.tar.gz
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
script:
- ./cmake-3.3.0-rc4-Linux-x86_64/bin/cmake .
- make -j5
- ./cmake-3.3.0-rc4-Linux-x86_64/bin/ctest .
os:
- linux